import type {
  CMSDestination,
  CMSDestinationSummary,
  CMSFAQ,
  CMSTourPackage,
} from './types'

const destinationSummary = (name: string, slug: string): CMSDestinationSummary => ({
  name,
  slug: { current: slug },
})

export const INITIAL_DESTINATIONS: CMSDestination[] = [
  {
    _id: 'fallback-munnar',
    name: 'Munnar',
    slug: { current: 'munnar' },
    heroTitle: 'Munnar Travel Guide',
    heroSubtitle: 'Plan a Kerala hill-country stay around tea landscapes, viewpoints and nature experiences.',
    heroImage: { asset: { url: '/destinations/d4.jpg' }, alt: 'Green hills and tea country in Munnar' },
    overview: 'Munnar is a hill destination in Kerala’s Western Ghats, known for tea-growing landscapes, cool highland weather and scenic drives. It is commonly combined with Kochi, Thekkady and Alleppey in a wider Kerala itinerary. The pace and sightseeing plan should be adjusted for weather, road conditions and the needs of each travelling group.',
    bestTimeToVisit: 'Munnar can be visited through much of the year. The cooler, generally drier months are popular for sightseeing, while the monsoon brings lush scenery along with heavier rain and possible disruption. Check the local forecast before travel.',
    recommendedDuration: 'Usually 2–3 nights, depending on the wider route and preferred pace.',
    placesToVisit: ['Tea-growing landscapes', 'Scenic viewpoints', 'Local markets and gardens'],
    thingsToDo: ['Take a relaxed scenic drive', 'Learn about the region’s tea heritage', 'Choose nature walks suited to current conditions'],
    howToReach: 'Munnar is reached by road. Kochi is a common arrival point for travellers combining Munnar with other Kerala destinations. Journey time varies with traffic, weather and stops.',
    travelTips: ['Carry a light layer for cooler evenings.', 'Allow flexibility during heavy rain.', 'Confirm attraction opening conditions locally.'],
    nearbyDestinations: [
      destinationSummary('Kochi (Cochin)', 'kochi'),
      destinationSummary('Thekkady', 'thekkady'),
    ],
    faqs: [
      { question: 'How many days are suitable for Munnar?', answer: 'Many itineraries allow two or three nights, but the right duration depends on your route and preferred pace.' },
      { question: 'Can Munnar be combined with Alleppey?', answer: 'Yes. Munnar and Alleppey are commonly included in a broader Kerala route, with travel arranged by road.' },
    ],
    seoTitle: 'Munnar Travel Guide | Places, Best Time & Kerala Packages',
    seoDescription: 'Plan a Munnar trip with a practical overview of places to visit, seasonal guidance, nearby destinations and Kerala packages.',
  },
  {
    _id: 'fallback-alleppey',
    name: 'Alleppey (Alappuzha)',
    slug: { current: 'alleppey' },
    heroTitle: 'Alleppey (Alappuzha) Travel Guide',
    heroSubtitle: 'Explore Kerala’s backwater landscape and plan a stay or houseboat experience responsibly.',
    heroImage: { asset: { url: '/destinations/d1.jpg' }, alt: 'Backwater landscape near Alleppey' },
    overview: 'Alleppey, officially Alappuzha, is a well-known gateway to Kerala’s backwaters. Visitors often include a day cruise, an overnight houseboat or a waterside stay as part of a route with Kochi, Munnar or Thekkady. Houseboat standards and operating arrangements vary, so inclusions should be confirmed in a written quotation.',
    bestTimeToVisit: 'The drier months are generally popular for backwater travel. Monsoon visits can be scenic but may involve heavier rain. Conditions and boat operations should be checked close to travel.',
    recommendedDuration: 'Usually 1–2 nights, depending on whether the plan includes a cruise or overnight stay.',
    placesToVisit: ['Backwater canals', 'Alappuzha town and waterfront', 'Nearby village landscapes'],
    thingsToDo: ['Take a backwater cruise', 'Enjoy waterside scenery', 'Combine the stay with a wider Kerala route'],
    howToReach: 'Alappuzha is connected by road and rail. Kochi is a common nearby arrival hub. Travel time depends on traffic and the selected route.',
    travelTips: ['Confirm boat type, meal plan and check-in details before booking.', 'Use sun and rain protection as appropriate.', 'Keep the itinerary flexible during severe weather.'],
    nearbyDestinations: [
      destinationSummary('Kochi (Cochin)', 'kochi'),
      destinationSummary('Thekkady', 'thekkady'),
    ],
    faqs: [
      { question: 'Is Alleppey the same as Alappuzha?', answer: 'Yes. Alappuzha is the official name, while Alleppey remains widely used by travellers.' },
      { question: 'Should I choose a day cruise or overnight houseboat?', answer: 'The choice depends on your schedule, comfort preferences and confirmed boat arrangements. Ask for the exact inclusions before booking.' },
    ],
    seoTitle: 'Alleppey Travel Guide | Backwaters & Kerala Packages',
    seoDescription: 'Explore Alleppey (Alappuzha) backwaters, practical seasonal advice, nearby destinations and relevant Kerala tour packages.',
  },
  {
    _id: 'fallback-thekkady',
    name: 'Thekkady',
    slug: { current: 'thekkady' },
    heroTitle: 'Thekkady Travel Guide',
    heroSubtitle: 'Plan a nature-focused Kerala stop around forest landscapes, spice country and locally available activities.',
    heroImage: { asset: { url: '/destinations/d2.jpg' }, alt: 'Forest landscape around Thekkady' },
    overview: 'Thekkady is a popular highland stop in Kerala, associated with the Periyar landscape, spice-growing areas and nature-based activities. It fits naturally between Munnar and the backwaters in many road itineraries. Activities are subject to local rules, weather, availability and official operating conditions.',
    bestTimeToVisit: 'Thekkady is visited year-round, with weather and activity conditions varying by season. Check official local information for forest-related activities before finalising a plan.',
    recommendedDuration: 'Usually 1–2 nights within a multi-destination Kerala itinerary.',
    placesToVisit: ['Periyar landscape', 'Spice-growing areas', 'Local viewpoints and markets'],
    thingsToDo: ['Explore available nature activities', 'Visit a spice-growing area', 'Plan a relaxed highland stay'],
    howToReach: 'Thekkady is generally reached by road and is often combined with Munnar or Alleppey. Journey times vary with hill-road and traffic conditions.',
    travelTips: ['Book regulated activities through authorised channels.', 'Follow local wildlife and forest guidance.', 'Carry rain protection when needed.'],
    nearbyDestinations: [
      destinationSummary('Munnar', 'munnar'),
      destinationSummary('Alleppey (Alappuzha)', 'alleppey'),
    ],
    faqs: [
      { question: 'How long should I stay in Thekkady?', answer: 'One or two nights suits many Kerala routes, depending on the activities available and your pace.' },
      { question: 'Are wildlife sightings guaranteed?', answer: 'No. Wildlife is unpredictable, and no responsible itinerary should guarantee a sighting.' },
    ],
    seoTitle: 'Thekkady Travel Guide | Things to Do & Kerala Packages',
    seoDescription: 'Plan a Thekkady visit with nature-focused guidance, nearby destinations and Kerala package ideas.',
  },
  {
    _id: 'fallback-kochi',
    name: 'Kochi (Cochin)',
    slug: { current: 'kochi' },
    heroTitle: 'Kochi (Cochin) Travel Guide',
    heroSubtitle: 'Discover a historic coastal city and a practical starting point for Kerala itineraries.',
    heroImage: { asset: { url: '/destinations/d3.jpg' }, alt: 'Coastal city scenery in Kochi' },
    overview: 'Kochi, also called Cochin, is a coastal city with historic neighbourhoods, cultural sites and strong transport connections. It is often the arrival or departure point for routes through Munnar, Thekkady and Alleppey. A city stay can be planned around interests and arrival times without overloading the first or final day.',
    bestTimeToVisit: 'Kochi is a year-round city destination. Outdoor sightseeing is often more comfortable in the drier months, while monsoon travel requires flexibility for rain.',
    recommendedDuration: 'Usually 1–2 nights, or a partial day when used as an arrival or departure hub.',
    placesToVisit: ['Historic neighbourhoods', 'Waterfront areas', 'Museums and cultural sites'],
    thingsToDo: ['Take a heritage-area walk', 'Explore local food and markets', 'Use the city as a base for a wider Kerala route'],
    howToReach: 'Kochi has air, rail and road connections. Select the station or airport appropriate to your onward route and allow time for urban traffic.',
    travelTips: ['Plan around arrival and departure times.', 'Dress appropriately for places of worship.', 'Allow extra time for city traffic.'],
    nearbyDestinations: [
      destinationSummary('Munnar', 'munnar'),
      destinationSummary('Alleppey (Alappuzha)', 'alleppey'),
    ],
    faqs: [
      { question: 'Is Kochi the same as Cochin?', answer: 'Kochi is the official name; Cochin is the older name and remains commonly used.' },
      { question: 'Is Kochi a good starting point for a Kerala tour?', answer: 'Yes. Its transport connections make it a common starting or finishing point for central Kerala routes.' },
    ],
    seoTitle: 'Kochi Travel Guide | Cochin Attractions & Kerala Packages',
    seoDescription: 'Plan a Kochi (Cochin) visit with practical sightseeing guidance, nearby destinations and Kerala tour routes.',
  },
]

const destinationRefs = (...slugs: string[]) =>
  INITIAL_DESTINATIONS.filter((destination) => slugs.includes(destination.slug.current))

export const INITIAL_PACKAGES: CMSTourPackage[] = [
  {
    _id: 'fallback-3n4d',
    title: '3 Nights / 4 Days Kerala Tour Package',
    slug: { current: '3-nights-4-days-kerala-tour-package' },
    shortSummary: 'A short Kerala itinerary template ready to be tailored after the preferred route and travel requirements are confirmed.',
    description: 'This short Kerala package is kept flexible because the route, accommodation, transport and inclusions require confirmation for each enquiry. Share your arrival point, travel dates and priorities to receive a verified itinerary and quotation.',
    duration: '3 Nights / 4 Days',
    nights: 3,
    days: 4,
    heroImage: { asset: { url: '/packages/Popular-Kerala.webp' }, alt: 'Kerala landscape for a short tour itinerary' },
    relatedDestinations: destinationRefs('kochi', 'munnar', 'alleppey'),
    faqs: [{ question: 'Can this itinerary be customised?', answer: 'Yes. The route and services are confirmed only after your dates, arrival point and preferences are reviewed.' }],
    seo: {
      seoTitle: '3 Nights 4 Days Kerala Tour Package | Custom Itinerary',
      seoDescription: 'Plan a custom 3 nights 4 days Kerala tour. Share your route, dates and stay preferences for a verified itinerary and quotation.',
      noindex: true,
    },
  },
  {
    _id: 'fallback-4n5d',
    title: '4 Nights / 5 Days Kerala Tour Package',
    slug: { current: '4-nights-5-days-kerala-tour-package' },
    tagline: 'Popular Kerala',
    shortSummary: 'A customisable Kerala route based on the existing Popular Kerala package.',
    description: 'The existing Popular Kerala package covers Kochi, Munnar, Thekkady and Alleppey across four nights and five days. Final hotel, transport, houseboat and meal details must be confirmed in the quotation.',
    duration: '4 Nights & 5 Days',
    nights: 4,
    days: 5,
    price: 12990,
    locations: ['Kochi', 'Munnar', 'Thekkady', 'Alleppey'],
    heroImage: { asset: { url: '/packages/Popular-Kerala.webp' }, alt: 'Popular Kerala tour route' },
    relatedDestinations: destinationRefs('kochi', 'munnar', 'thekkady', 'alleppey'),
    faqs: [{ question: 'What is included in the displayed starting price?', answer: 'Package inclusions vary by dates and traveller requirements. Request a written quotation before booking.' }],
    seo: {
      seoTitle: '4 Nights 5 Days Kerala Tour Package | Custom Trip',
      seoDescription: 'Explore a 4 nights 5 days Kerala route covering Kochi, Munnar, Thekkady and Alleppey. Request a customised quotation.',
    },
  },
  {
    _id: 'fallback-5n6d',
    title: '5 Nights / 6 Days Munnar–Thekkady–Alleppey Package',
    slug: { current: '5-nights-6-days-munnar-thekkady-alleppey-package' },
    tagline: 'Amazing Kerala',
    shortSummary: 'A six-day Kerala route based on the existing Amazing Kerala package.',
    description: 'This existing package route combines Kochi, Munnar, Thekkady and Alleppey over five nights and six days. The day-wise plan and all commercial inclusions require confirmation in the final quotation.',
    duration: '5 Nights & 6 Days',
    nights: 5,
    days: 6,
    price: 16990,
    locations: ['Kochi', 'Munnar', 'Thekkady', 'Alleppey'],
    heroImage: { asset: { url: '/packages/Amazing-Kerala.webp' }, alt: 'Munnar Thekkady and Alleppey Kerala route' },
    relatedDestinations: destinationRefs('kochi', 'munnar', 'thekkady', 'alleppey'),
    faqs: [{ question: 'Is the route fixed?', answer: 'The published route is a starting point and can be adjusted after travel dates and preferences are confirmed.' }],
    seo: {
      seoTitle: '5 Nights 6 Days Kerala Package | Munnar & Alleppey',
      seoDescription: 'Plan a 5 nights 6 days Kerala trip through Munnar, Thekkady and Alleppey with a customised itinerary and quote.',
    },
  },
  {
    _id: 'fallback-honeymoon-houseboat',
    title: 'Kerala Honeymoon Package with Houseboat',
    slug: { current: 'kerala-honeymoon-package-with-houseboat' },
    tagline: 'Romantic Kerala',
    shortSummary: 'A couple-focused Kerala route based on the existing Romantic Kerala package.',
    description: 'The existing Romantic Kerala package combines Kochi, Munnar, Thekkady and Alleppey over four nights and five days and includes a houseboat reference. Boat type, privacy, stays, meals, transport and romantic arrangements must be confirmed in writing.',
    duration: '4 Nights & 5 Days',
    nights: 4,
    days: 5,
    price: 18990,
    locations: ['Kochi', 'Munnar', 'Thekkady', 'Alleppey'],
    accommodation: 'Houseboat',
    heroImage: { asset: { url: '/packages/Romantic-Kerala.webp' }, alt: 'Kerala honeymoon route with backwater experience' },
    houseboatInformation: 'Houseboat type, privacy, route, operating hours, meals and other inclusions are confirmed in the written quotation.',
    relatedDestinations: destinationRefs('kochi', 'munnar', 'thekkady', 'alleppey'),
    faqs: [{ question: 'Is a private houseboat guaranteed?', answer: 'No. Houseboat privacy and category must be specifically requested and confirmed in the written quotation.' }],
    seo: {
      seoTitle: 'Kerala Honeymoon Package with Houseboat | Custom Trip',
      seoDescription: 'Explore a Kerala honeymoon route with Munnar, Thekkady and an Alleppey houseboat option. Request verified inclusions and a custom quote.',
    },
  },
]

export const HUB_FAQS: CMSFAQ[] = [
  { question: 'Can Kerala tour packages be customised?', answer: 'Yes. Routes, duration and services can be planned around your dates, arrival point and traveller needs. Final inclusions are confirmed in writing.' },
  { question: 'How many days are suitable for a Kerala trip?', answer: 'Four to seven days suits many first-time routes, while shorter and longer plans are possible. The best duration depends on how many destinations you want to include.' },
  { question: 'When is a good time to visit Kerala?', answer: 'Kerala is visited year-round. Drier months are popular for general sightseeing, while monsoon travel offers greener scenery but needs more flexibility.' },
]
